apiVersion: v1

kind: Service

metadata:

  name: image-processing-api

  namespace: {{ .Values.namespace }}

spec:

  selector:

    app: image-processing-api

  ports:

  - port: 80

    targetPort: 8000

  type: ClusterIP