name: Deploy To EKS

on:

  push:

    branches:
      - main

env:

  AWS_REGION: us-east-1

  ECR_REPOSITORY: image-processing-repo

  EKS_CLUSTER_NAME: image-processing-eks

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code

      uses: actions/checkout@v4

    - name: Configure AWS Credentials

      uses: aws-actions/configure-aws-credentials@v4

      with:

        aws-access-key-id:
          ${{ secrets.AWS_ACCESS_KEY_ID }}

        aws-secret-access-key:
          ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        aws-region:
          ${{ env.AWS_REGION }}

    - name: Login To Amazon ECR

      id: login-ecr

      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image

      run: |

        docker build \
        -t $ECR_REPOSITORY:${{ github.sha }} .

    - name: Tag Docker Image

      run: |

        docker tag \
        $ECR_REPOSITORY:${{ github.sha }} \
        ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

    - name: Push Docker Image

      run: |

        docker push \
        ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

    - name: Install kubectl

      uses: azure/setup-kubectl@v4

      with:

        version: latest

    - name: Install Helm

      uses: azure/setup-helm@v4

    - name: Configure kubeconfig

      run: |

        aws eks update-kubeconfig \
        --region $AWS_REGION \
        --name $EKS_CLUSTER_NAME

    - name: Verify Cluster Access

      run: |

        kubectl get nodes

    - name: Deploy Using Helm

      run: |

        helm upgrade --install image-processing \
        ./helm/image-processing \
        --namespace image-processing \
        --create-namespace \
        --set image.repository=${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY \
        --set image.tag=${{ github.sha }}